/**
 * Types and data shapes for the Community Health Worker (CHW) Module.
 * Using JSDoc for IDE autocompletion without needing TypeScript.
 */

/**
 * @typedef {Object} CHWWorker
 * @property {string} workerId - Unique ID for the CHW.
 * @property {string} workerName - Name of the CHW.
 * @property {string} village - Village or operating area.
 * @property {string} doctorNumber - WhatsApp number of the doctor to send reports to.
 */

/**
 * @typedef {Object} DiagnosticResult
 * @property {string} id - Unique ID for this specific test run.
 * @property {string} moduleName - Name of the module (e.g. 'SkinAnalyzer', 'EyePredictor').
 * @property {string} summary - The clinical summary generated by the AI.
 * @property {'normal' | 'warning' | 'critical'} riskLevel - The risk level of the findings.
 * @property {string} timestamp - ISO timestamp of when the test was completed.
 * @property {Object} [rawData] - Optional raw data from the module.
 */

/**
 * @typedef {Object} Patient
 * @property {string} id - Unique UUID for the patient.
 * @property {string} name - Name of the patient.
 * @property {number} age - Age of the patient.
 * @property {'Male' | 'Female' | 'Other'} gender - Gender of the patient.
 * @property {string} chiefComplaint - Primary reason for visit.
 * @property {DiagnosticResult[]} results - Array of completed diagnostic tests.
 * @property {'normal' | 'warning' | 'critical'} overallRisk - Highest risk level across all results.
 * @property {string} timestamp - When the patient was registered.
 */

/**
 * @typedef {Object} CHWSession
 * @property {CHWWorker} worker - The worker conducting the session.
 * @property {string} sessionStart - ISO timestamp of session start.
 * @property {Patient[]} patients - Roster of patients seen in this session.
 */

export {}
